name: CI

on:
  push:
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9, 3.10]
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python}}
        architecture: x64
    - uses: actions-rs/cargo@v1
      with:
        command: test
    - uses: messense/maturin-action@v1
      with:
        manylinux: auto
        command: build
        args: --release -o dist
    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        name: wheels-${{matrix-python}}
        path: dist
